### PR TITLE
Cris week1

### PR DESCRIPTION
**Pull request by CS9490**
Added in our database. It will need further discussion such as what some fields' types need to be. We also need to still set up some basic CRUD operations. Additionally cleaned up main.dart and got rid of the beginning boilerplate comments.

### CODE REVIEW

**Comment by SheinH** [comment]
I made some changes to the schema to reflect JournalEntry.dart and I made the transcriptions its own table.

🤔🤔🤔

I'm not sure how to properly represent the transcriptions in the schema. The problem is that users might want to transcribe multiple times or combine speech & text input. We have a few options

1. Allow users to transcribe only once per entry - Makes our life easier but will be annoying for user since they can't append to a transcription.
2. Don't store or represent the audio in the schema - We just use the transcription as an input method only and don't hold onto the audio or store the audio in the db

**Comment by SheinH** [comment]
Thinking about it further, I don't think anybody actually likes playing back recordings of their own voice. It's probably better to just treat transcription as an input method only and not store recordings at all.

**Review by armyf35 — DISMISSED** [review]
Looks good so far. @SheinH what are your thoughts?

**Comment by CS9490** [comment]
Looks good on my end, and yes I definitely agree, I doubt people will want to listen to themselves talking 😅. Either way, good work, this is solid.

**Review by CS9490 — COMMENTED** [review]
Nice migration setup. Looks good on my end. We may need to change soem of the fields in the future, but as of now, this is fine.

**Review by SheinH — APPROVED** [review]
Looks good Merged!

**Pull request merged**
